FROM nginx:latest

LABEL org.opencontainers.image.authors="harald@leinders.de"

RUN mkdir -p /var/www/html

COPY html /var/www/html/
COPY resources/nginx/index.html /var/www/html/index.html
COPY resources/nginx/default.conf /etc/nginx/conf.d/default.conf

WORKDIR /var/www/html
