entryPoints:
  http80:
    address: ":80"

api:
  dashboard: true
  insecure: false

providers:
  docker:
    watch: true
    network: traefik
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    defaultRule: "Host(`{{ index .Labels \"com.docker.compose.service\"}}.mk.local.nil`)"

  file:
    filename: traefik_dynamic.yml
    watch: true

log:
  # level: DEBUG
  # level: INFO
  # level: WARN
  level: ERROR